apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: git@github.com:balex42/openshift-local-gitops.git
    targetRevision: HEAD
    path: apps/eso
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
