apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-operator-catalog
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://redhat-developer.github.io/redhat-helm-charts
      chart: ibm-operator-catalog-enablement
      targetRevision: 1.1.0
      helm:
        valueFiles:
          - $values/apps/ibm-operator-catalog/values.yaml
    - repoURL: git@github.com:balex42/openshift-local-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ibm-operator-catalog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
