apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitops-operator-app.yaml
  - vault-app.yaml
  - eso-app.yaml
  - openshift-ai-app.yaml
  - ibm-operator-catalog-app.yaml
